version: '2'

services:
 web:
   restart: always
   build: ./web
   image: ww12358/dy_web:release01
   expose:
     - "8000"
   volumes:
     - /usr/src/app/creek
     - /home/sean/Nutstore/excels:/usr/src/app/creek/data
   command: >
      bash -c "gunicorn --pythonpath=/usr/src/app/creek/ app:app -w 2 -b 0.0.0.0:8000
      | /usr/sbin/cron && tail -f /usr/src/app/creek/data/log/dy.log"


 nginx:
   restart: always
   build: ./nginx
   image: ww12358/dy_nginx:release02
   expose:
      - "80"
   ports:
     - "80:80"
   volumes:
     - /usr/src/app/creek/static/
   volumes_from:
     - web
   depends_on:
     - web


